config/routes.rb
Rails.application.routes.draw do
  
  get '/auth/google_oauth2/callback', to: 'authentications#create'

  devise_for :super_users, :controllers => { sessions: 'super_users/sessions'}
  devise_for :users#, controllers: {omniauth_callbacks: 'omniauth_callbacks' }
  resources :articles do
    get :avatar, on: :member
  end

  resources :welcomes
  resources :admins

  root 'welcomes#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="col-xs-9 container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Blog</a>
    </div>
    <ul class="nav navbar-nav">
      <% if current_user %>
          <li><a href="#">Home</a></li>
      <% end %>
    </ul>
  </div>
  <div class="col-xs-3">
    <ul class="nav navbar-nav pull-right">
      <% if current_user %>
          <li><a href="<%= edit_user_registration_path %>">Hi, <%= current_user.email %></a></li>
          <li><a href="<%= destroy_user_session_path %>" data-method="delete">Sign Out</a></li>

      <% elsif current_super_user %>

          <li><a href="<%= edit_super_user_registration_path %>">Hi, <%= current_super_user.email %></a></li>
          <li><a href="<%= destroy_super_user_session_path %>" data-method="delete">Sign Out</a></li>

      <% else %>
          <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign In<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="<%= new_user_session_path %>">User</a></li>
              <li><a href="<%= new_super_user_session_path %>">Admin</a></li>
            </ul>
          </li>

      <% end %>
    </ul>
  </div>
</nav>
<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>
</body>
</html>